# Generated by Django 5.0.4 on 2024-04-16 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('translated_languages', models.JSONField(default=list)),
                ('slug', models.CharField(max_length=20)),
                ('banners', models.JSONField(default=list)),
                ('promotional_sliders', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('icon', models.CharField(default='default_icon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(default='1111', max_length=20)),
                ('customer_name', models.CharField(default='cutomer_name', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('cancelled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('language', models.CharField(max_length=10)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_gateway', models.CharField(max_length=100)),
                ('altered_payment_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logistics_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address_zip', models.CharField(max_length=20)),
                ('shipping_address_city', models.CharField(max_length=100)),
                ('shipping_address_state', models.CharField(max_length=100)),
                ('shipping_address_country', models.CharField(max_length=100)),
                ('shipping_address_street_address', models.CharField(max_length=255)),
                ('billing_address_zip', models.CharField(default='default billing zip', max_length=20)),
                ('billing_address_city', models.CharField(default='default billing city', max_length=100)),
                ('billing_address_state', models.CharField(default='default billing address', max_length=100)),
                ('billing_address_country', models.CharField(default='default billing country', max_length=100)),
                ('billing_address_street_address', models.CharField(default='default billing address street', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(default='default-slug', max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('language', models.CharField(max_length=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('status', models.CharField(default='publish', max_length=20)),
                ('product_type', models.CharField(default='simple', max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.JSONField(default=dict)),
                ('gallery', models.JSONField(default=list)),
                ('popular_product', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.type')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('positive_feedbacks_count', models.IntegerField(default=0)),
                ('negative_feedbacks_count', models.IntegerField(default=0)),
                ('my_feedback', models.CharField(blank=True, max_length=10, null=True)),
                ('abusive_reports_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('photos', models.JSONField(default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('positive_feedbacks_count', models.IntegerField(default=0)),
                ('negative_feedbacks_count', models.IntegerField(default=0)),
                ('my_feedback', models.CharField(blank=True, max_length=10, null=True)),
                ('abusive_reports_count', models.IntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
